# Generated by Django 2.2.5 on 2019-09-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190922_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesdescription',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
