# Generated by Django 2.2.5 on 2019-09-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_classesdescription_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='testomonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
