# Generated by Django 2.2.5 on 2019-09-22 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_testomonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='blogdetail',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
