# Generated by Django 2.2.5 on 2019-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190922_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='description',
            field=models.TextField(),
        ),
    ]
