# Generated by Django 2.2.5 on 2019-09-23 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_yogatype1'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogatype1',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
