# Generated by Django 2.2.5 on 2019-09-23 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_yogatype1_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogatype1',
            name='time',
        ),
        migrations.AddField(
            model_name='yogatype1',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
