# Generated by Django 2.2.5 on 2019-09-23 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190923_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogatype1',
            name='date',
        ),
        migrations.AddField(
            model_name='yogatype1',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
