# Generated by Django 2.2.5 on 2019-09-26 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_ourinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(default='describe here')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
