# Generated by Django 2.2.5 on 2019-09-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_detailedinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
