# Generated by Django 2.2.5 on 2019-11-01 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20191101_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('details', models.TextField(verbose_name='here is details')),
            ],
        ),
        migrations.DeleteModel(
            name='YogaType1',
        ),
        migrations.AddField(
            model_name='detailedinformation',
            name='class_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='website.ClassDetails'),
        ),
    ]
