# Generated by Django 2.2.5 on 2019-11-04 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20191101_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='classdetails',
            name='details',
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='description',
            field=models.TextField(default='describe here'),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='classdetails',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='DetailedInformation',
        ),
    ]
