# Generated by Django 2.2.5 on 2019-11-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20191104_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsingle',
            name='description',
            field=models.TextField(default='describe here'),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='image_title',
            field=models.TextField(default='title'),
        ),
    ]
