# Generated by Django 2.2.5 on 2019-11-04 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20191104_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsingle',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
