# Generated by Django 2.2.5 on 2019-11-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20191104_0644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDetail',
        ),
    ]
