# Generated by Django 2.2.5 on 2019-11-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_delete_blogdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='website',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='description',
            field=models.TextField(default='describe here'),
        ),
    ]
