# Generated by Django 2.2.5 on 2019-11-06 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_postcomment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
