# Generated by Django 2.2.5 on 2019-11-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_blogsingle_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsingle',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
