# Generated by Django 2.2.5 on 2019-11-06 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20191106_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetails',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_details', to='website.ClassType'),
        ),
    ]
