# Generated by Django 2.2.5 on 2019-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_classdetails_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
