# Generated by Django 2.2.5 on 2019-11-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_bannerheading'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='YogaBenefits',
        ),
    ]
