# Generated by Django 2.2.5 on 2019-11-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20191106_0903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoreDetails',
            new_name='MoreYogaBenefits',
        ),
    ]
