# Generated by Django 2.2.5 on 2019-11-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20191106_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='SubscribeDescription',
        ),
    ]
