# Generated by Django 2.2.5 on 2019-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_ourinformation_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YogaDetail',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
