# Generated by Django 2.2.5 on 2019-11-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_answer_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
