# Generated by Django 2.2.5 on 2019-11-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20191108_0541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
