# Generated by Django 2.2.5 on 2019-11-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_delete_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainersDetail',
            new_name='TrainersSectionHeading',
        ),
    ]
