# Generated by Django 2.2.5 on 2019-11-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_auto_20191108_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='AboutBlog',
        ),
    ]
