# Generated by Django 2.2.5 on 2019-11-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20191108_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainersSectionHeading',
            new_name='TrainerSectionHeading',
        ),
    ]
