# Generated by Django 2.2.5 on 2019-12-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
