# Generated by Django 2.2.5 on 2019-12-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
