# Generated by Django 2.2.5 on 2019-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_auto_20191223_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
